services:
  icecast:
    build:
      context: ./
      dockerfile: ./dockerfiles/Dockerfile_solo
      args:
        - VERSION=2.5-beta3
    container_name: icecast
    restart: always
    ports:
      - 8000:8000
      - 8443:8443
    environment:
      - "TZ=Europe/Moscow"
      - ICECAST_SOURCE_PASSWORD
      - ICECAST_ADMIN_PASSWORD
      - ICECAST_RELAY_PASSWORD
      - ICECAST_HOSTNAME=omfm.ru

