services:
  omfmapi:
    container_name: omfmAPI
    build:
      context: ./
      dockerfile: ./docker/omfmapi/Dockerfile
    depends_on:
      - centrifugo
    environment:
      - "TZ=Europe/Moscow"
    user: node:node
    volumes:
      - ./docker/omfmapi/app/playlist:/home/node/app/playlist
      - ./docker/omfmapi/app/db:/home/node/app/db
      # - /var/log/nginx:/var/log/nginx:ro
    restart: always
    secrets:
      - source: api_username
      - source: api_password
      - source: icecast_username
      - source: icecast_password
    ports:
       - 127.0.0.1:9999:9999
    networks:
       - omfm-network
    logging:
      driver: "json-file"
      options:
        max-size: "1m"  
        max-file: "3"

  listeners_monitor:
    build:
      context: ./
      dockerfile: ./docker/listeners_monitor/Dockerfile
    container_name: listeners_monitor
    networks:
      - omfm-network
    environment:
      TZ: "Europe/Moscow"
      STREAM_NAMES: "omfm,cdp"
    volumes:
      - /var/log/nginx:/var/log/nginx:ro
    restart: always
    secrets:
      - source: api_username
      - source: api_password
      - source: icecast_username
      - source: icecast_password
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"

  centrifugo:
    container_name: centrifugo
    restart: always
    image: centrifugo/centrifugo:latest
    volumes:
      - ./docker/centrifugo/config.toml:/centrifugo/config.toml
    command: centrifugo -c config.toml
    ports:
       - 127.0.0.1:9998:9998
    # network_mode: "host"
    networks:
       - omfm-network
    depends_on:
      - icecast
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"


  liquidsoap:
    build:
      context: ./
      dockerfile: ./docker/liquidsoap/Dockerfile
      args:
        - "USER_UID=${USER_UID:-1000}"
        - "USER_GID=${USER_GID:-1000}"
    #image: savonet/liquidsoap-alpine:10453cf
    #image: savonet/liquidsoap-alpine:v2.2.5
    # user: 1000:1000
    container_name: liquidsoap
    environment:
      - "TZ=Europe/Moscow"
    command:
      - /usr/bin/docker-entrypoint
    volumes:
      #- /var/www/html/omfmsse/omFM_build/docker/liquidsoap/rootfs/home/radio/liquidsoap/omfm/index.liq:/home/radio/liquidsoap/omfm/index.liq
      #- /var/www/html/omfmsse/omFM_build/docker/liquidsoap/rootfs/home/radio/liquidsoap/omfm/omfm.liq:/home/radio/liquidsoap/omfm/omfm.liq
      #- /var/www/html/omfmsse/omFM_build/docker/liquidsoap/rootfs/home/radio/playlist:/home/radio/playlist
      - /var/www/html/omfm/hls/omfm:/home/radio/liquidsoap/omfm/hls
      - /var/www/html/omfm/hls/cdp:/home/radio/liquidsoap/cdp/hls
      - /mnt/GoogleDrive:/mnt/GoogleDrive:ro
      #- /mnt/GoogleDriveMusic:/mnt/GoogleDrive:ro
      - /home/radio/music:/home/radio/music
      #- ./docker/liquidsoap/rootfs/home/radio/liquidsoap/omfm/log:/home/radio/liquidsoap/omfm/log
      #- ./docker/liquidsoap/rootfs/home/radio/liquidsoap/cdp/log:/home/radio/liquidsoap/cdp/log
      - ./docker/liquidsoap/rootfs/home/radio/playlist:/home/radio/playlist
      - ./docker/liquidsoap/log:/var/log/supervisor
      # - ./docker/liquidsoap/rootfs/home/radio/liquidsoap/test_gaps/log:/home/radio/liquidsoap/test_gaps/log
    ports:
       - 127.0.0.1:8007:8007
       - 127.0.0.1:8008:8008
       - 127.0.0.1:1234:1234
       - 127.0.0.1:1235:1235
    networks:
      - omfm-network
    depends_on:
      - omfmapi
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"

  icecast:
    #image: libretime/icecast:2.5-beta3-alpine
    build:
      context: ./
      dockerfile: ./docker/icecast/Dockerfile
      args:
        - VERSION=
    container_name: icecast
    restart: always
    volumes:
      - ./docker/icecast/config/concat-om.pem:/usr/share/icecast/concat-om.pem
    networks:
      - omfm-network
    ports:
      - 8000:8000
      - 8443:8443
    environment:
      - "TZ=Europe/Moscow"
      - ICECAST_SOURCE_PASSWORD
      - ICECAST_ADMIN_PASSWORD
      - ICECAST_RELAY_PASSWORD
      - ICECAST_HOSTNAME
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"


networks:
  omfm-network:
    enable_ipv6: true # This is the standard modern toggle
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

secrets:
  api_username:
    file: ./docker/listeners_monitor/api_username.txt
  api_password:
    file: ./docker/listeners_monitor/api_password.txt
  icecast_username:
    file: ./docker/listeners_monitor/icecast_username.txt
  icecast_password:
    file: ./docker/listeners_monitor/icecast_password.txt

