[supervisord]
user=root
nodaemon=false
logfile=/var/log/supervisor/supervisord.log ; (main log file;default $CWD/supervisord.log)
logfile_maxbytes=10MB        ; (max main logfile bytes b4 rotation;default 50MB)
logfile_backups=5           ; (num of main logfile rotation backups;default 10)
loglevel=info                ; (log level;default info; others: debug,warn,trace)
pidfile=/var/run/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
minfds=1024                  ; (min. avail startup file descriptors;default 1024)
minprocs=200                 ; (min. avail process descriptors;default 200)

[program:liquidsoap-omfm]
command=/usr/bin/liquidsoap /home/radio/liquidsoap/omfm/index.liq
#environment=MEMTRACE="/home/radio/liquidsoap/omfm/liq-trace"
user=radio
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/liquidsoap-omfm.log
stdout_logfile_maxbytes=5MB ; Maximum size of the log file before rotation
stdout_logfile_backups=5    ; Number of backup log files to keep
stdout_capture_maxbytes=1MB

[program:liquidsoap-cdp]
command=/usr/bin/liquidsoap /home/radio/liquidsoap/cdp/index.liq
#environment=MEMTRACE="/home/radio/liquidsoap/cdp/liq-trace-cdp"
user=radio
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/liquidsoap-cdp.log
stdout_logfile_maxbytes=5MB ; Maximum size of the log file before rotation
stdout_logfile_backups=5    ; Number of backup log files to keep
stdout_capture_maxbytes=1MB


